server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: candidate-service
  datasource:
    url: jdbc:postgresql://localhost:5432/candidate-db
    username: postgres
    password: QweAsdZxc@209
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
service:
  job-url: http://job-service:8082/api/v1/jobService