server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: job-application-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job-application-db
    username: postgres
    password: QweAsdZxc@209
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
service:
  job-url: http://localhost:8082/api/v1/jobService
  candidate-url: http://localhost:8081/api/v1/candidateService
